codecov.yml

For now test coverage is only informative and the GitHub checks shown in the review are annoying. For the time being, we can include this change to disable those checks globally from the "Files changed" view. Once we actually start caring for code coverage, we can revert this.
Documentation: https://docs.codecov.com/docs/github-checks

Disable Codecov GitHub checks

---

Cargo.toml
examples/hello-world/src/main.rs
examples/todo-list/Cargo.toml
examples/todo-list/src/main.rs
examples/todo-list/templates/index.html
flareon-macros/Cargo.toml
flareon-macros/src/form.rs
flareon-macros/src/lib.rs
flareon-macros/tests/compile_tests.rs
flareon-macros/tests/ui/derive_form.rs
flareon/Cargo.toml
flareon/src/error.rs
flareon/src/forms.rs
flareon/src/lib.rs
flareon/src/prelude.rs
flareon/src/private.rs
flareon/src/request.rs
flareon/src/router.rs
flareon/src/router/path.rs

Quite a big PR, but at this stage of the project it's difficult to make any significant changes while also separating it into logical blocks.
This adds:
- HTTP GET and POST Form support with easy-to-use derive macro
- Much better routing, with support for path params, and ability to get a URL for given view name
- Simple support for the Askama template engine
- A simple TODO app example showcasing the features listed above

feat: add form support and better routing; implement TODO app example

---

Cargo.lock
Cargo.toml
examples/todo-list/src/main.rs
flareon-codegen/src/model.rs
flareon-macros/src/model.rs
flareon/Cargo.toml
flareon/src/db.rs
flareon/src/db/db_sqlite.rs
flareon/src/db/fields.rs
flareon/src/db/query.rs
flareon/tests/db.rs

This limits our choices for supported data types stored in the DB (e.g. no support for i8/u8). It's easiest to make the switch now, so now we differentiate between DB backends.

refactor: stop using sqlx::any

---

Cargo.lock
Cargo.toml
examples/todo-list/src/migrations/m_0001_initial.rs
flareon-cli/src/migration_generator.rs
flareon/Cargo.toml
flareon/src/db.rs
flareon/src/db/fields.rs
flareon/src/db/migrations.rs
flareon/src/lib.rs
flareon/src/router.rs
flareon/tests/db.rs

`Body` and `Operation` are not supposed to be constructed directly by the user, so they were hidden behind a private field in a struct.
This also adds some new tests and docs.

chore: hide some enums' internals

---

Cargo.lock
Cargo.toml
examples/sessions/Cargo.toml
examples/sessions/src/main.rs
examples/sessions/templates/index.html
examples/sessions/templates/name.html
examples/todo-list/src/main.rs
flareon/src/lib.rs
flareon/src/middleware.rs
flareon/src/request.rs

This is based on the tower-sessions crate, but provides a slightly simpler API (that should be extended in the following commits).

feat: add initial session support

---

examples/hello-world/src/main.rs
examples/sessions/src/main.rs
examples/todo-list/src/main.rs
flareon/src/error.rs
flareon/src/error_page.rs
flareon/src/lib.rs
flareon/src/request.rs
flareon/src/router.rs
flareon/tests/router.rs

The user should never have to check the exact type of error, and this will provide us with a much easier semver-compatibility.
The main reason for the change though is to store additional generic data in the Error struct (namely a backtrace - will come in the next change).

refactor: hide Error details behind a private ErrorRepr enum

---

flareon/src/auth.rs
flareon/src/db.rs
flareon/src/db/fields.rs
flareon/src/db/migrations.rs
flareon/src/db/query.rs
flareon/tests/db.rs

This changes the name of as_sea_query_value() to to_sea_query_value() to better conform with Rust's typical method naming.

feat(db): add support for Vec<u8>; small refactor

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
flareon/Cargo.toml

This has several upsides:
- We don't end up being in a broken state when the latest version of a dependency is yanked;
- We give more freedom to the user to choose the versions they need (and, for instance, can't upgrade for whatever reason);
This also comes with a new CI job to check if the project builds with the minimal versions.

chore: make versions in Cargo.toml less specific

---

.github/workflows/rust.yml
Cargo.toml
README.md
compose.yml
flareon-cli/src/migration_generator.rs
flareon-macros/src/dbtest.rs
flareon-macros/src/lib.rs
flareon/src/auth.rs
flareon/src/auth/db.rs
flareon/src/db.rs
flareon/src/db/fields.rs
flareon/src/db/impl_postgres.rs
flareon/src/db/impl_sqlite.rs
flareon/src/db/migrations.rs
flareon/src/lib.rs
flareon/src/test.rs
flareon/tests/auth.rs
flareon/tests/db.rs

In addition to that, this also adds tests that use Postgres, and a way to run raw SQL queries.
There's some opportunity to do some deduplication between Sqlite and Postgres code, but let's wait for it until MySQL support lands.

feat(orm): postgres support

---

.github/workflows/audit.yml

This also fixes the `schedule` property being on the wrong indentation level.

ci: fix security audit check

---

Cargo.lock
Cargo.toml
flareon-cli/Cargo.toml
flareon-macros/Cargo.toml
flareon/Cargo.toml
flareon/src/router/path.rs

This also removes the `regex` dependency as it was easily replaced with some simple text-handling code.
This PR reduces the number of compiled units for the examples/sessions crate from 312 to 252. This allows me to reduce the clean build time from 22.7 seconds to 18.8 seconds on my laptop.

chore: remove unused dependency features

---

flareon/Cargo.toml
flareon/src/lib.rs

See rust-lang/rust#43781. This enables infoboxes like "Available on crate feature XXX only." in the documentation generated using `cargo doc` on nightly, or by building on docs.rs.
This can be tested with:
```shell
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps --all-features
```

docs: enable nightly-only docsrs

---

Cargo.toml

cargo-machete doesn't check workspace-level dependencies, but [the new RustRover](https://www.jetbrains.com/rust/whatsnew/#page__content-new-rust-specific-features) does!

chore: remove unused deps from the workspace Cargo.toml

---

Cargo.lock
examples/admin/Cargo.toml
examples/admin/src/main.rs
examples/hello-world/Cargo.toml
examples/hello-world/src/main.rs
examples/sessions/Cargo.toml
examples/sessions/src/main.rs
examples/todo-list/Cargo.toml
examples/todo-list/src/main.rs
flareon-macros/src/lib.rs
flareon-macros/src/main_fn.rs
flareon-macros/tests/compile_tests.rs
flareon-macros/tests/ui/attr_main.rs
flareon-macros/tests/ui/attr_main_args.rs
flareon-macros/tests/ui/attr_main_args.stderr
flareon/Cargo.toml
flareon/src/lib.rs
flareon/src/private.rs
flareon/src/test.rs
flareon/tests/router.rs

This is the first step in making Flareon an actual "framework" rather than just a library. This macro currently doesn't do much now, but eventually we'd like to have an entire CLI that would be automatically generated for each Flareon project and would allow to do some common operations (run server, run migrations, copy static files to a directory, etc.), as well as allow Flareon users to define their own ones.

feat: implement flareon::main macro for easy framework bootstrapping

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
clippy.toml
compose.yml
flareon-macros/src/dbtest.rs
flareon/Cargo.toml
flareon/build.rs
flareon/src/admin.rs
flareon/src/auth.rs
flareon/src/config.rs
flareon/src/db.rs
flareon/src/db/fields.rs
flareon/src/db/impl_mysql.rs
flareon/src/db/impl_postgres.rs
flareon/src/db/impl_sqlite.rs
flareon/src/db/migrations.rs
flareon/src/db/sea_query_db.rs
flareon/src/error.rs
flareon/src/lib.rs
flareon/src/request.rs
flareon/src/test.rs
flareon/tests/db.rs

This also deduplicates the database code and adds feature flags that can enable and disable the database backends (or remove the ORM altogether).
This commit also adds a cargo hack step to the CI that checks if the project can be compiled using any subset of the features.

feat: MySQL support

---

examples/todo-list/src/migrations/m_0001_initial.rs
flareon-cli/src/migration_generator.rs
flareon/src/auth/db/migrations/m_0001_initial.rs
flareon/src/db.rs
flareon/src/db/migrations.rs
flareon/src/db/migrations/sorter.rs
flareon/src/lib.rs
flareon/src/test.rs
rustfmt.toml

For now the system only really create dependency on the previous migration in the app. Eventually we'll extend this to handle ForeignKeys and other relationship types as well.

feat(orm): implement dependencies for migrations

---

.github/workflows/rust.yml
flareon-cli/tests/migration_generator.rs
flareon-macros/src/dbtest.rs
flareon-macros/tests/compile_tests.rs
flareon/src/auth.rs
flareon/src/auth/db.rs
flareon/src/lib.rs
flareon/src/static_files.rs
flareon/tests/db.rs
flareon/tests/flareon_project.rs
flareon/tests/router.rs

`db` and `password_hash` tests would not finish, investigating why can be a future endeavor

ci: setup miri

---

.cargo/audit.toml

This disables checking for `RUSTSEC-2023-0071` in our cargo-audit config. This really only generates noise in **all the PRs** for now, as we already have #72 to track this. Until a fix is available, there's no point in spamming all PRs with CI failures because of this.

chore(cargo-audit): disable RSA advisory

---

Cargo.lock
Cargo.toml

Our contributions were merged and released, so using a patched version from git is no longer necessary.

chore(deps): use upstream `fake` again

---

.github/workflows/rust.yml

This is done to fix https://github.com/cot-rs/cot/actions/runs/12728982874/job/35480378199#step:8:441
Also, it runs *only* ignored tests to speed up the pipeline.

ci: run only external deps tests

---

Cargo.lock
Cargo.toml
LICENSE-MIT
cot/Cargo.toml
cot/src/admin.rs
cot/src/error.rs
cot/src/error_page.rs
cot/src/lib.rs
cot/src/middleware.rs
cot/src/private.rs
cot/src/request.rs
cot/src/router.rs
cot/src/router/path.rs
cot/src/utils.rs
cot/templates/admin/model_list.html
examples/admin/Cargo.toml
examples/admin/src/main.rs
examples/admin/templates/index.html
examples/admin/templates/name.html
examples/sessions/src/main.rs
examples/sessions/templates/name.html
examples/todo-list/src/main.rs
examples/todo-list/templates/index.html

This fixes a lot of stuff found when writing the documentation page:
* Add live reloading middleware
* Add support for response body-modifying middlewares
* Rename reverse_str!() to reverse!() and change param format a bit to be more intuitive
* Rename reverse!() to reverse_redirect!() since getting a URL as string is far more common than returning a redirect response
* Fixes around error handling, examples, documentation, etc.
* Updated year in LICENSE-MIT
After this initial batch of fixes, next PRs will be one feature per commit.

feat: various fixes for writing actual projects with the framework

---

cot-cli/Cargo.toml

This will be more convenient for the users, and won't produce conflicts anyway (since the `cot` crate is a library).

chore: rename cot-cli executable to just `cot`

---

cot/src/auth/db.rs
cot/src/db.rs

This was missed when `Auto` structure was added to the project.

refactor: use Auto<T> for `id` in `DatabaseUser`

---

cot/src/test.rs

Postgres tests very frequently fail because supposedly there's a session still running when dropping the test database (which doesn't make much sense, because closing the only session and THEN dropping the database should be done sequentially in a single future).
Single this is becoming increasingly annoying and I don't have any good idea how to fix this properly, and this is only affecting tests, I think it's fine to just do `WITH (FORCE)` and forget about the issue for now.
See also: https://github.com/orgs/cot-rs/projects/2?pane=issue&itemId=94050368

test: use DROP ... WITH (FORCE) in tests

---

Cargo.lock
Cargo.toml

A new version has been released, so there's no longer any need to use our fork.

chore(deps): switch back to upstream tower-livereload

---

cot/src/error.rs
cot/src/request.rs
cot/src/request/path_params_deserializer.rs
examples/todo-list/src/main.rs

This makes it much easier to retrieve the path params from the URLs, by implementing a clean API based on serde that is capable of deserializing tuples, structs, and single values while providing a nice error handling.

feat: add path params deserializer

---

cot-cli/src/new_project.rs
cot/src/admin.rs
cot/src/db.rs
cot/src/router.rs
cot/src/router/path.rs
cot/tests/router.rs
examples/todo-list/src/main.rs

This follows a similar change in axum 0.8 (although we have an in-house solution to parse URL params). This has numerous advantages:
* It is more similar to what Rust users expect, given it's the same format as used in `println!()`, `format!()`, etc.
* It is also the same format as used in OpenAPI specs
* The old format didn't support putting an actual colon in the URL; the new one supports escaping with double braces

feat: switch to Rust-like syntax for URL params

---

cot/src/auth.rs
cot/src/auth/db.rs

Followup to the discussion: https://github.com/cot-rs/cot/pull/111#discussion_r1936328781

feat: separate auth errors for invalid UserId/credentials types

---

codecov.yml

Codecov marks all PRs that do not hit the coverage target as failing, which isn't very useful. This sets the threshold to 0.5% meaning that anything that doesn't drop the overall coverage by 0.5% or more will suceed.

ci: set codecov coverage threshold

---

cot/src/router/path.rs

This simple change makes the framework users' code a bit easier to write, especially when writing templates where you don't see compiler errors easily.

feat: take values by reference in the reverse_param_map macro

---

cot-macros/src/form.rs
cot-macros/src/lib.rs
cot/src/admin.rs
cot/src/form.rs
cot/src/form/fields.rs
cot/src/html.rs
cot/src/lib.rs
cot/src/private.rs
cot/templates/admin/login.html
cot/tests/form.rs

There's really no point of having a separate trait that just returns Strings (even if they're wrapped in Html newtype).
One of the advantages of rinja over askama is that we can mark types as HTML-safe, so they don't get escaped. So now, after removing Render and using plain old Display, instead of writing `{{ form_field.render()|safe }}` we can do just `{{ form_field }}`.

refactor: remove Render trait

---

.github/workflows/rust.yml

A nice bonus is code coverage for doctests, too.

chore(ci): use cargo-llvm-cov for code coverage

---

Cargo.lock
Cargo.toml
cot/src/db.rs

fix: the build after `fake` semver-incompatible change in v3.2

---

cot-cli/src/project_template/src/main.rs
cot/src/handler.rs
cot/src/middleware.rs
cot/src/project.rs
cot/src/static_files.rs
cot/src/test.rs
examples/admin/src/main.rs
examples/todo-list/src/main.rs

It was inconsistent with the actual structure name and confusing, hence the last-minute change.

refactor: rename `app_context` to just `context`

---

cot-macros/Cargo.toml

We won't be able to release without this.

fix: use path dev-dependency for cot in cot-macros

---

Cargo.lock
cot/Cargo.toml
cot/src/error_page.rs

This PR enhances error logging in Cot by implementing structured logging with the tracing crate. The goal is to improve observability and enable better integration with OpenTelemetry for monitoring errors in production services.
Changes:
- Implement structured error logging with tracing spans
- Add request context and metadata to error logs
- Include backtrace information in error spans
- Add comprehensive test coverage for logging functionality
- Maintain backwards compatibility with existing error pages
Added new tests that verify:
- Error logging with request context
- Error logging without request context
- Panic logging
- Not found logging
- Integration with error page handlers
related Issues
Implements better error monitoring as discussed in issue #160

feat(error): enhance error logging with tracing integration

---

cot-cli/src/migration_generator.rs
cot-cli/src/new_project.rs
cot-cli/src/utils.rs

Fixes #146: 
This PR adds user-friendly status messages to CLI operations, making it clearer what actions are being performed during execution.
Changes:
- Added StatusType enum with different operation states (Creating, Adding, etc.)
- Implemented color-coded terminal output for different operations
- Added status messages throughout the codebase for operations like creating migrations, adding fields, etc.
- Ensured messages are concise and helpful for end users
- Added placeholders for future additions
- Added tests to ensure the added code works as intended

feat: Add status messages to CLI operations for better user feedback

---

cot/src/db.rs
cot/src/db/relations.rs
cot/src/form.rs

This attribute causes the panic message to point to the location of the caller, rather than to the location where the panic is. This makes more useful panic messages, as they will point to users' codes rather than the internal Cot code.

feat: add #[track_caller] to `unwrap`s for better panic messages

---

cot-cli/src/new_project.rs
cot/src/private.rs

cot and cot-cli crates' version do not necessarily have to be in sync (strictly speaking, cot-cli's version can be higher than cot's) so we need to make sure we put the latest cot crate version in user's Cargo.toml. Otherwise, build failures might happen because of invalid dependencies.

fix: use cot's version instead of cli's when creating a new project

---

cot-cli/src/new_project.rs

PR #213 has properly decoupled cot's and cot-cli's versions but haven't updated the unit test that tests the Cargo.toml generated by `cot new` (which now fails in #215).

fix: unit test after 25785c27

---

.github/workflows/rust.yml

This will prevent merging the code if it raises any compiler or clippy warnings, but still won't break the code immediately when a new lint is introduced, or won't prevent you from prototyping easily.

chore: deny all rustc/clippy warnings in the CI

---

.github/workflows/rust.yml

Clippy doesn't actually seem to be properly run, so reverting to just running `cargo clippy` directly.

ci: remove clippy-action

---

README.md

Apart from the badges, I'm thinking of automatic listing of sponsors in README, I found two pre-made actions for that:
- https://github.com/antfu-collective/sponsorkit?tab=readme-ov-file#tiers-renderer
- https://github.com/marketplace/actions/add-github-sponsors-to-readme
What do you think of those @m4tx?

chore: add sponsor badges to README.md

---

release-plz.toml

Changes to the config:
- do not generate changelog for `cot-codegen` and `cot-macros`
- extract security changes to separate category
- preprocess commit messages to include links, so that the changelog is useful outside of GitHub
- removed pointless comments
- always output breaking commits
With those changes, the changelog for this version for `cot` will look like this:
- cycle session ID on login, flush session on logout ([#246](https://github.com/cot-rs/cot/pull/246))
- add a user-friendly message for AddrInUse error ([#233](https://github.com/cot-rs/cot/pull/233))
- add support for remove field in automatic migration generator ([#232](https://github.com/cot-rs/cot/pull/232))
- add basic pagination support for admin panel ([#217](https://github.com/cot-rs/cot/pull/217))
- support …

chore: modify how changelog is generated

---

cot-cli/src/migration_generator.rs
cot-cli/src/utils.rs
cot-cli/tests/migration_generator.rs
cot/src/test.rs

This also fixes `--app-name` param trying to find existing packages (its original use is to override the app name even when it does not correspond to any existing crate).
The change also makes `migration make` not work when ran in a workspace, instead forcing the user to choose a specific crate inside. In the future, a proper support should be added instead (possibly taking dependencies between crates into account) and an option to specify a crate name without having to specify its path.

fix(cli): migration generator not working in inner project directories

---

cot-cli/src/migration_generator.rs

Before the change all models triggered the detection, generating useless messages.

fix(cli): modified models detection

---

.github/workflows/rust.yml
compose.yml

This doesn't change the behavior as the tests have still been run with `--all-features`, but this should lead to a slightly more acurrate timings in CI.

ci: run `cargo build` with `--all-features` in CI

---

examples/admin/src/main.rs

The second session config overrides the first which sets `secure` to true. Safari doesn't handle this well.

Fix session config in admin app example

---

cot/src/middleware.rs

525c1295 broke the SessionMiddleware in a way that it does no longer respects the `secure` option. This fixes the problem and adds a test to make sure it doesn't come back again.

fix: actually use SessionMiddleware config

---

.github/workflows/rust.yml

This PR adds `sccache` for improved caching as well as fixes a bunch of other issues.
- The `Build & test` stage is faster by around 30-60 seconds on average. 
- Excluding Miri, the second stage of jobs is faster by around 1.5-3.5 minutes on average.
- Binaries are no longer saved by `Swatinem/rust-cache` to reduce the cache size.
- Set the shared key to a fixed value so that the cache created in the first stage can actually be used by the second stage.
The most impactful further work is speeding up Windows build and Miri test, but that can be a topic for another PR.

ci: use sccache

---

.github/workflows/rust.yml

This should fix the Rust CI not being run after approving the workflows for new contributors.

chore(ci): run Rust CI on workflow_dispatch

---

Cargo.lock
Cargo.toml
cot/Cargo.toml
cot/src/admin.rs
cot/src/auth.rs
cot/src/auth/db.rs
cot/src/common_types.rs
cot/src/form.rs
cot/src/form/fields.rs
cot/src/form/types.rs
cot/src/lib.rs
cot/tests/auth.rs

Add support for form email fields. This wraps over the `EmailAddress` type in the [email_address crate](https://docs.rs/email_address/latest/email_address/index.html).
Also refactors and deprecates `cot::auth::Password` which is replaced by `cot::form::types::Passsword`.
Example usage:
```rust
use cot::db::{model, Auto, Model};
use cot::form::types::{Email, Password};
use cot::auth::PasswordHash
[derive(Debug, Form)]
struct SignupForm {
fullname: String,
email: Email,
username: String,
password1: Password,
password2: Password,
}
#[derive(Debug, Clone)]
#[model]
struct User {
#[model(primary_key)]
id: Auto<i32>,
name: String,
username: String,
email: Email,
password: PasswordHash,
}
```

Form support for Email Field

---

cot/src/form.rs
cot/src/form/fields.rs

```rust
#[derive(Debug, Form)]
struct TodoForm {
#[form(opt(max_length = 100))]
title: String,
foo: f32,
#[form(opt(max = 40.5))]
bar: f64
#[form(opt(min=10.0 ,max = 40.0))]
range: f64,
}
```

implement `AsFormField` for floating point types

---

cot-codegen/src/lib.rs
cot-codegen/src/model.rs
cot-codegen/src/symbol_resolver.rs
cot-macros/src/model.rs

In database models, if you used `ForeignKey<Self>` you'd get an error as described by https://github.com/cot-rs/cot/issues/298
In this PR, I added a check in the symbol resolver to check for any generic `Self` and replace it with the struct name.
This also affects migration generation which now references `Self` with full struct crate name.

fix: ForeignKey<Self> doesn't compileFix self foreignkey

---

cot/src/response/into_response.rs

`Html` already owns its containing `String`, and `IntoResponse::into_response()` consumes `self`, so there is no need to clone the string.

fix: don't clone string in `<Html as IntoResponse>`

---

cot/Cargo.toml
cot/src/common_types.rs
cot/src/form.rs
cot/src/form/fields.rs

Accidentally closed #339 by overwriting the source branch's content.
This just contains a squash of the original code.

feat: add validated `Url` type (#339)

---

cot/src/config.rs

This way, we'll force people to use builders or TOML configs to create the instances of the structures (instead of providing a third option for no clear reason), and adding fields to already existing structs will stop being a breaking change.

chore!: add `#[non_exhaustive]` to config structs

---

cot/src/config.rs

When reading from a Toml file, session config knobs like `path` and `name` do not use default values set in the `build` constructor. This PR should fix that

fix: custom Default implementation for `SessionMiddlewareConfig`

---

.github/workflows/rust.yml

With each added feature flag, the number of checks that needs to be perfomed increased exponentially. This causes the "Build with each feature combination" job to take up 1.5 hours!
This commit sets the depth (max number of features tested at once) to 3, decreasing the total number of checks from 794 to 232, which should greatly reduce the pipeline times without reducing the check usefulness too much.
We might be forced to reduce this even more (to two) in the future if we keep increasing the number of feature flags. We might think about splitting the code into more crates then.

chore(ci): limit the max number of features tested `cargo check`

---

cot/src/session/store/redis.rs

Ignored doctests are not even compiled, so they are at higher risk of being out-of-date. If build failure is deliberate, there is `compile_fail` annotation to indicate this.

fix: ignored doctest

---

cot/src/form.rs

We might want to extend them in the future, and I can't see much of a reason for the users to construct these themselves (although matching on them can be useful!)

chore!: add `#[non_exhaustive]` to `FormError` variants

---

cot/src/middleware.rs
cot/src/middleware/live_reload.rs

The module still reexports the type at the same place, but the middleware has been extracted to make quite a big file a little bit smaller.
Also includes some basic tests for the middleware and tiny doc fixes.

chore: extract `LiveReloadMiddleware` to a separate file
